### ISSUE TITLE
'advance_y' set but not used 

### ISSUE THREAD

**Issue by EmVee381** [ArthurSonzogni/smk-starter#2]
hello 
i am getting this error, it is part of smk library not? could you help me how to override it or make it compile on latest emscripten... please? thx

 smk-starter/build_emscripten/_deps/smk-src/src/smk/Text.cpp:110:9: error: variable 'advance_y' set but not used [-Werror,-Wunused-but-set-variable]
  float advance_y = font_->line_height();
        ^

**Comment by EmVee381** [comment]
i just forked smk and disabled Werror and i am satisfied... :)

**Comment by ArthurSonzogni** [comment]
Thanks for reporting this!
(I can't reproduce with my compiler)

Fixed.

**Comment by EmVee381** [comment]
thank you for quick reply :) and thank you for your work on this project!
